// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNonVfoxSdk(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddNonVfoxSdk'](arg1, arg2, arg3);
}

export function AddVfoxToPath() {
  return window['go']['app']['App']['AddVfoxToPath']();
}

export function CheckAnyPathOverride() {
  return window['go']['app']['App']['CheckAnyPathOverride']();
}

export function CheckPluginPathOverride(arg1) {
  return window['go']['app']['App']['CheckPluginPathOverride'](arg1);
}

export function CheckPluginWin11CompatMode(arg1) {
  return window['go']['app']['App']['CheckPluginWin11CompatMode'](arg1);
}

export function CheckVfoxInPath() {
  return window['go']['app']['App']['CheckVfoxInPath']();
}

export function CheckWin11CompatMode() {
  return window['go']['app']['App']['CheckWin11CompatMode']();
}

export function DetectSdkPathVersion(arg1, arg2) {
  return window['go']['app']['App']['DetectSdkPathVersion'](arg1, arg2);
}

export function ExportCurrentEnvironmentSdks() {
  return window['go']['app']['App']['ExportCurrentEnvironmentSdks']();
}

export function GetActiveCustomSdk(arg1) {
  return window['go']['app']['App']['GetActiveCustomSdk'](arg1);
}

export function GetAddedPlugins() {
  return window['go']['app']['App']['GetAddedPlugins']();
}

export function GetAllSdks() {
  return window['go']['app']['App']['GetAllSdks']();
}

export function GetAvailablePlugins() {
  return window['go']['app']['App']['GetAvailablePlugins']();
}

export function GetCachedSystemSdks() {
  return window['go']['app']['App']['GetCachedSystemSdks']();
}

export function GetDownloadPathInfo() {
  return window['go']['app']['App']['GetDownloadPathInfo']();
}

export function GetInstalledSdks() {
  return window['go']['app']['App']['GetInstalledSdks']();
}

export function GetNonVfoxSdks() {
  return window['go']['app']['App']['GetNonVfoxSdks']();
}

export function GetNonVfoxSdksMap() {
  return window['go']['app']['App']['GetNonVfoxSdksMap']();
}

export function GetPlatformInfo() {
  return window['go']['app']['App']['GetPlatformInfo']();
}

export function GetSdkDetail(arg1) {
  return window['go']['app']['App']['GetSdkDetail'](arg1);
}

export function GetVersionPath(arg1, arg2) {
  return window['go']['app']['App']['GetVersionPath'](arg1, arg2);
}

export function HijackPluginSystemPath(arg1) {
  return window['go']['app']['App']['HijackPluginSystemPath'](arg1);
}

export function HijackSystemPath(arg1, arg2) {
  return window['go']['app']['App']['HijackSystemPath'](arg1, arg2);
}

export function ImportSdkEnvironmentFromTxt() {
  return window['go']['app']['App']['ImportSdkEnvironmentFromTxt']();
}

export function InstallVersion(arg1, arg2) {
  return window['go']['app']['App']['InstallVersion'](arg1, arg2);
}

export function PreviewCurrentEnvironmentSdks() {
  return window['go']['app']['App']['PreviewCurrentEnvironmentSdks']();
}

export function RefreshAvailablePlugins() {
  return window['go']['app']['App']['RefreshAvailablePlugins']();
}

export function RemoveNonVfoxSdk(arg1, arg2) {
  return window['go']['app']['App']['RemoveNonVfoxSdk'](arg1, arg2);
}

export function RemovePlugin(arg1) {
  return window['go']['app']['App']['RemovePlugin'](arg1);
}

export function RemovePluginWithOptions(arg1, arg2) {
  return window['go']['app']['App']['RemovePluginWithOptions'](arg1, arg2);
}

export function RemoveVfoxFromPath() {
  return window['go']['app']['App']['RemoveVfoxFromPath']();
}

export function ResetDownloadPath() {
  return window['go']['app']['App']['ResetDownloadPath']();
}

export function ResetDownloadPathWithMigration(arg1) {
  return window['go']['app']['App']['ResetDownloadPathWithMigration'](arg1);
}

export function RestorePluginSystemPath(arg1) {
  return window['go']['app']['App']['RestorePluginSystemPath'](arg1);
}

export function RestoreSystemPath(arg1) {
  return window['go']['app']['App']['RestoreSystemPath'](arg1);
}

export function RunVfoxCommand(arg1) {
  return window['go']['app']['App']['RunVfoxCommand'](arg1);
}

export function RunVfoxWithProgress(arg1) {
  return window['go']['app']['App']['RunVfoxWithProgress'](arg1);
}

export function ScanSystemSdks() {
  return window['go']['app']['App']['ScanSystemSdks']();
}

export function SearchVersions(arg1) {
  return window['go']['app']['App']['SearchVersions'](arg1);
}

export function SelectDownloadPath() {
  return window['go']['app']['App']['SelectDownloadPath']();
}

export function SetDownloadPath(arg1) {
  return window['go']['app']['App']['SetDownloadPath'](arg1);
}

export function SetDownloadPathWithMigration(arg1, arg2) {
  return window['go']['app']['App']['SetDownloadPathWithMigration'](arg1, arg2);
}

export function UninstallVersion(arg1, arg2) {
  return window['go']['app']['App']['UninstallVersion'](arg1, arg2);
}

export function UnuseVersion(arg1) {
  return window['go']['app']['App']['UnuseVersion'](arg1);
}

export function UseCustomSdk(arg1, arg2) {
  return window['go']['app']['App']['UseCustomSdk'](arg1, arg2);
}

export function UseVersion(arg1, arg2) {
  return window['go']['app']['App']['UseVersion'](arg1, arg2);
}
