// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddNonVfoxSdk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddVfoxToPath():Promise<void>;

export function CheckAnyPathOverride():Promise<boolean>;

export function CheckPluginPathOverride(arg1:string):Promise<boolean>;

export function CheckPluginWin11CompatMode(arg1:string):Promise<boolean>;

export function CheckVfoxInPath():Promise<boolean>;

export function CheckWin11CompatMode():Promise<boolean>;

export function DetectSdkPathVersion(arg1:string,arg2:string):Promise<string>;

export function ExportCurrentEnvironmentSdks():Promise<string>;

export function GetActiveCustomSdk(arg1:string):Promise<string>;

export function GetAddedPlugins():Promise<Array<string>>;

export function GetAllSdks():Promise<Array<main.SdkInfo>>;

export function GetAvailablePlugins():Promise<Array<main.PluginInfo>>;

export function GetCachedSystemSdks():Promise<Array<main.SdkInfo>>;

export function GetDownloadPathInfo():Promise<main.DownloadPathInfo>;

export function GetInstalledSdks():Promise<Array<main.SdkInfo>>;

export function GetNonVfoxSdks():Promise<Record<string, Array<main.SdkInfo>>>;

export function GetNonVfoxSdksMap():Promise<Record<string, Array<main.SdkInfo>>>;

export function GetPlatformInfo():Promise<main.PlatformInfo>;

export function GetSdkDetail(arg1:string):Promise<main.SdkDetail>;

export function GetVersionPath(arg1:string,arg2:string):Promise<string>;

export function HijackPluginSystemPath(arg1:string):Promise<void>;

export function HijackSystemPath(arg1:string,arg2:string):Promise<void>;

export function ImportSdkEnvironmentFromTxt():Promise<main.SdkEnvironmentImportResult>;

export function InstallVersion(arg1:string,arg2:string):Promise<void>;

export function PreviewCurrentEnvironmentSdks():Promise<string>;

export function RefreshAvailablePlugins():Promise<Array<main.PluginInfo>>;

export function RemoveNonVfoxSdk(arg1:string,arg2:string):Promise<void>;

export function RemovePlugin(arg1:string):Promise<void>;

export function RemovePluginWithOptions(arg1:string,arg2:string):Promise<void>;

export function RemoveVfoxFromPath():Promise<void>;

export function ResetDownloadPath():Promise<main.DownloadPathInfo>;

export function RestorePluginSystemPath(arg1:string):Promise<void>;

export function RestoreSystemPath(arg1:string):Promise<void>;

export function RunVfoxCommand(arg1:Array<string>):Promise<string>;

export function RunVfoxWithProgress(arg1:Array<string>):Promise<void>;

export function ScanSystemSdks():Promise<void>;

export function SearchVersions(arg1:string):Promise<Array<string>>;

export function SelectDownloadPath():Promise<string>;

export function SetDownloadPath(arg1:string):Promise<main.DownloadPathInfo>;

export function UninstallVersion(arg1:string,arg2:string):Promise<void>;

export function UnuseVersion(arg1:string):Promise<string>;

export function UseCustomSdk(arg1:string,arg2:string):Promise<string>;

export function UseVersion(arg1:string,arg2:string):Promise<string>;
